### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by bphenriques** [samgriesemer/vim-roam#1]
Hello! 

I am looking for `org-roam` counterparts within vim and I stumbled upon your project 👀  The premise looks great! 

Is this project actively being maintained? If so, do you have some quick guidelines on how to set it up and/or a video demonstration?

**Comment by samgriesemer** [comment]
Hi Bruno,

Thanks for checking in on the project. Yes I'm still actively developing the plugin, although the documentation is certainly lacking at this point. The project has mostly been for personal use but I've been meaning to make it more accessible now that it's getting some attention. Hoping to find some time in the next week or two to detail the install process and plugin usage; I'll update this issue once I get that pushed. 

Let me know if you have any other questions/suggestions/etc in the meantime. Thanks again for taking a look at the plugin!

**Comment by bphenriques** [comment]
Thank you for the feedback! 🙇   Let me know how can I help!

**Comment by ysl2** [comment]
Hi, could you please teach me how to use this plugin?

Thank you :-)

**Comment by samgriesemer** [comment]
Some decent documentation is coming soon...currently rewriting the core note graph component of the plugin and establishing a coherent set of mappings. Should be much easier to get started once that's pushed

**Comment by alextes** [comment]
Just signaling my interest! Roam is too expensive for me at the moment but the core set of features work great in Roam. Looking for the vim equivalent this seems closest.

**Comment by samgriesemer** [comment]
@bphenriques @ysl2 @alextes Thought I'd update this issue along with the recent repo rewrite and improved README. If you're still interested in the plugin, it should now be a little easier to get started. Feel free to re-open this issue with any additional questions/feedback. Thanks!
