### ISSUE TITLE
Suggestion/Question on wiki.vim branch

### ISSUE THREAD

**Issue by bybor** [samgriesemer/vim-roam#2]
Hello!

I noticed that you have a separate dev branch of `wiki.vim` to be used in `vim-roam`.

Would you consider trying to merge your changes into the original repository?

Some that I noticed:
- saving buffer on navigating away;
- modifying a file name on link navigating (if not exists). For me this means following Zettelkasten recommendation on prepending unique ID in the beginning of internal link;
- optimizing backlinks search.

These all look like great additions (that can be enabled or disabled by user).

I personally switched from `vimwiki` to `wiki.vim` not so long ago. The main reason for this is being able to use `asciidoc` as notes format. Almost every other wiki/roam solution sticks to `markdown`.

And your changes look like something I'd like to try, but that I can hardly do myself.

Thank you!

**Comment by samgriesemer** [comment]
Hi @bybor,

Thanks for taking a look at the plugin and `wiki.vim` fork. For the features you mentioned:

- __Saving buffer on navigation__: this feature has actually already been merged into the original project. Check out the `g:wiki_write_on_nav` option in the [documentation](https://github.com/lervag/wiki.vim/blob/master/doc/wiki.txt#L532).
- __Link navigation transformations__: as far as I'm aware the original plugin cannot do this, so your suggestion is a good one. I'll try to write up a PR soon and see about adding custom link nav transformations to the option set.
- __Optimized backlinks search__: this is the primary goal of Vim-roam. I'm currently reworking the backlink system for the plugin and it'll be mostly separate from the `wiki.vim` implementation, so merging it will likely not match either project scope. In fact at some point `vim-roam` may be entirely independent of `wiki.vim`; the backlink processing can be mostly separated from the outer wiki environment.

Hope that helps! I'll update this issue if/when I get those link transformations merged into the original repo.

**Comment by bybor** [comment]
Thank you very much for your answer, I appreciate it!

It all makes sense. At some point i thought that it could be possible to use `sqlite` to index backlinks. Extra dependency is bad, but it's cross-platform and could improve performance. It could also be easily "fetched" as text and updated in a similar manner. 

May be one could treat backlinks as a special kind of tags, which is a more universal way of doing it. Since `tag` can point to a specific location in file it would mimic "link to any block" feature available in _Roam Research_ (AFAIK, have never used).

It will be great if you find it possible to not enforce `markdown` format, but make `vim-roam` format-agnostic. But it will be great to see `vim-roam` growing in the first place. :) 

Thank you

**Comment by samgriesemer** [comment]
Hey @bybor, finally got around to pushing out an update. Some of the new details in the README on [link transformations](https://github.com/samgriesemer/vim-roam#alternative-syntax-and-link-transformations) might be of interest based on your original questions.

> It will be great if you find it possible to not enforce markdown format, but make vim-roam format-agnostic.

I agree, although I think the plugin will depend on Pandoc's `commonmark` parser for the foreseeable future. Commonmark is very general, though, and Vim-roam only currently extracts file components like lists and paragraphs. There's a lot of overlap there with other wiki formats so I expect the hard Markdown requirement could be lifted.

> At some point i thought that it could be possible to use sqlite to index backlinks.

`sqlite` is an interesting direction to consider. Right now the main bottleneck is Pandoc parsing, so I don't imagine performance would be too different from the current Python dictionary cache approach+pickling.

Thanks for your feedback! Hopefully the repo is a little more navigable now.
