### ISSUE TITLE
installation procedure?

### ISSUE THREAD

**Issue by absurdist** [samgriesemer/vim-roam#3]
Hello Sam,

Thanks for making this available. 

Do you have any notes on how to install vim-roam?
(I'm running on windows)

I'm trying to get it running and trying to get to the bottom of what dependencies and config I need.
I'll keep a list here of what I've done for anyone who comes across this:

nvim on windows, in init.vim

"some of these dependencies actually from vimwiki
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " this install didn't actually work had to install in powershell using chocko
Plug 'junegunn/fzf.vim'
Plug 'vimwiki/vimwiki'
Plug 'iamcco/markdown-preview.nvim'
Plug 'samgriesemer/vim-roam'

then

```
:PlugInstall
```

in 

.vimrc

```
let g:wiki_root = '~/wiki'
let g:wiki_mappings_use_defaults = 1
```
also:

python -m pip install -e git+https://github.com/samgriesemer/panja#egg=panja
choco install fzf
pip install dill
pip install misaka

current error

```
Error detected while processing function roam#init#option:
line    5:
E117: Unknown function: wiki#u#extend_recursive
E117: Unknown function: wiki#u#extend_recursive

```

Thanks Mat

**Comment by dzungtran89** [comment]
@absurdist did you try to update the plug `https://github.com/samgriesemer/wiki.vim`? This func was added in [f9478f95](https://github.com/samgriesemer/wiki.vim/commit/f9478f95de79cab13b3bff871e717519bfef7ebc)

**Comment by absurdist** [comment]
Thank you @dzungtran89. No I didn't! I was using lervag/wiki.vim. I'll try you suggestion.

**Comment by samgriesemer** [comment]
Hey @absurdist,

Thanks for giving the plugin a try. Unfortunately it's been a bit of a mess in terms of dependencies for some time, and I've never really detailed a clear install procedure. I can also say I've never attempted to work with the plugin on Windows, so there may be unexpected behavior there.

In any case, I'll be pushing a condensed version of the plugin with better documentation and a clearer install procedure in the coming days. Not sure if you got things up and running a few days ago, but it should be easier with the coming push.

**Comment by absurdist** [comment]
@samgriesemer 
Thanks for replying Sam, I don't have it up and running yet, but intend to have another attempt this weekend.

**Comment by samgriesemer** [comment]
@absurdist I just pushed a pretty large rewrite + more detailed README. If you're still interested in getting things up and running, hopefully things are a bit easier to follow now. Unfortunately I have not tested on a Windows machine so do let me know if you give it a shot!
